# Generated by Django 2.0.6 on 2018-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
